name: coverage
on:
  pull_request:
    paths:
    - '**.rs'
    - '**/Cargo.toml'
    - '**/Cargo.lock'
    - .github/workflows/coverage.yml
  push:
    branches:
    - master
jobs:
  tarpaulin:
    name: tarpaulin
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-
    - uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-git-
    - uses: actions/cache@v1
      with:
        path: target/debug
        key: ${{ runner.os }}-target-tarpaulin-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-target-tarpaulin-
    - uses: actions-rs/tarpaulin@v0.1
      with:
        version: latest
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cobertura.xml
    - run: |
        cargo install cargo-cache --no-default-features --features ci-autoclean
        cargo-cache
